### ISSUE TITLE
Tracking issue: Rethinking RedrawRequested 

### ISSUE THREAD

**Issue by goddessfreya** [rust-windowing/winit#1082]
This issue tracks the implementation of the RedrawRequested API changes that were discussed in #1041. PRs implementing this change should be made against the `redraw-requested-2.0` branch, and we'll merge that branch onto `master` once it's implemented on all platforms.

- [x] Public API changed
- [x] Implemented on all platforms
  - [x] Windows - #1050
  - [x] macOS - #1235
  - [x] iOS - #1299
  - [x] Linux X11 - #1062 
  - [x] Linux Wayland - #1237 
  - [x] Web - #1301
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented.

**Comment by mtak-** [comment]
#1133 gets iOS 90% of the way there. There will need to be a separate (trivial) pr to actually send out the events.

**Comment by hecrj** [comment]
I can try to get this working on macOS. Is there anything I should be specially aware of?

**Comment by Osspial** [comment]
@mtak- the `redraw-requested-2.0` branch now contains #1133. Would it be possible to open a PR getting the iOS implementation the rest of the way there?

**Comment by Osspial** [comment]
@aleksijuvani You've got some experience with iOS programming. Could you see about implementing this on iOS?

@ryanisaacg Could you implement this on the web?

**Comment by aleksijuvani** [comment]
I'm no longer working with Rust these days, so I don't have a strong incentive to work on this. I can help with reviewing the pull request when it's done, but I won't be implementing this myself.

**Comment by Osspial** [comment]
Wow, that's... all the platforms done. I'll get this ready to merge within the next day or so.
