### ISSUE TITLE
Tracking issue for `WindowBuilder::with_outer_position`

### ISSUE THREAD

**Issue by murarth** [rust-windowing/winit#1190]
This issue tracks the implementation of `WindowBuilder::with_outer_position`, proposed in #806. PRs implementing this change should be made against the `with_outer_position` branch.

* [x] Public API (#1189) ([direct link](https://github.com/rust-windowing/winit/blob/271f1d5fa445a95f2f0968130fcea959b2656a20/src/window.rs#L117-L125))
* [ ] Changelog Entry
* [ ] Platform-specific implementations
  * [x] Unix X11 (#1189)
  * [x] Unix Wayland (no effect)
  * [ ] MacOS
  * [x] Windows
  * [ ] iOS
  * [ ] Android
  * [ ] WASM

**Comment by sumit0190** [comment]
Is someone already on this for Windows? I have some local changes (using `SetWindowPos`) that I could easily sync with master once this goes in.

**Comment by ZeGentzy** [comment]
Afaik, no one has mentioned anything.

**Comment by emilk** [comment]
I would love to have this (on mac)

**Comment by stephentalley** [comment]
Did work on this fizzle out? Could we have a partial fix, even if it's just for X11/Windows?

**Comment by msiglreith** [comment]
[`WindowBuilder::with_position`](https://docs.rs/winit/0.25.0/winit/window/struct.WindowBuilder.html#method.with_position) got introduced in 0.25, which covers this issues I think. On MacOS, it doesn't seem to be possible to specify the outer position due to decorations but on Windows/X11 it will set the outer position.

(PR: https://github.com/rust-windowing/winit/pull/1866)

**Comment by emilk** [comment]
@msiglreith I just tested this now, and it works, even on my Mac! 🥳 

Maybe this can be closed!?

**Comment by msiglreith** [comment]
nice, thanks for testing!
