### ISSUE TITLE
Browser support tracking

### ISSUE THREAD

**Issue by daxpedda** [rust-windowing/winit#2875]
## [`Element.requestFullscreen`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) returns `Promise`

[Source](https://github.com/rust-windowing/winit/blob/fc046add78f676118886ee6ab00684913a2895e1/src/platform_impl/web/web_sys/canvas.rs#L426-L439)
Relevant PR: #2751
[MDN Compatibility Table](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#browser_compatibility)
[Caniuse](https://caniuse.com/mdn-api_element_requestfullscreen_returns_promise)

Requires Safari v16.4.
See [Apple's documentation for supported devices](https://support.apple.com/en-us/HT213411).

## [`MediaQueryList`](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList) inherits `EventTarget`

[Source](https://github.com/rust-windowing/winit/blob/fc046add78f676118886ee6ab00684913a2895e1/src/platform_impl/web/web_sys/media_query_handle.rs#L23-L28)
Relevant PR: #2850.
[MDN Compatibility Table](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#browser_compatibility)
[Caniuse](https://caniuse.com/mdn-api_mediaquerylist_change_event)

Requires Safari v14.
See [Apple's documentation for supported devices](https://support.apple.com/en-us/HT211348).

## [`resolution`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/resolution) media feature

[Source](https://github.com/rust-windowing/winit/blob/fc046add78f676118886ee6ab00684913a2895e1/src/platform_impl/web/web_sys/scaling.rs#L56-L61)
[MDN Compatibility Table](https://github.com/rust-windowing/winit/blob/fc046add78f676118886ee6ab00684913a2895e1/src/platform_impl/web/web_sys/scaling.rs#L56-L61)
[Caniuse](https://caniuse.com/css-media-resolution)

Requires Safari v16.
See [Apple's documentation for supported devices](https://support.apple.com/en-us/HT213411).

## [`PointerEvent.getCoalescedEvents()`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents) 

[Source](https://github.com/rust-windowing/winit/blob/fc046add78f676118886ee6ab00684913a2895e1/src/platform_impl/web/web_sys/pointer.rs#L200-L209)
Relevant PR: #2840
[MDN Compatibility Table](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents#browser_compatibility)
[Caniuse](https://caniuse.com/mdn-api_pointerevent_getcoalescedevents)
[WPT](https://wpt.fyi/results/pointerevents/coalesced_events_attributes.html?label=master&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D)

- [ ] Safari: [Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=210454)

## Correct [`MouseEvent.movementX/Y`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementX) in coalesced events

Relevant PR: #2871

- [ ] Firefox: [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1753724)

## `pointerrawupdate` event

[Source](https://github.com/rust-windowing/winit/blob/fc046add78f676118886ee6ab00684913a2895e1/src/platform_impl/web/web_sys/pointer.rs#L315-L335)
Relevant PR: #2847
[Caniuse](https://caniuse.com/mdn-api_element_pointerrawupdate_event)
[WPT](https://wpt.fyi/results/pointerevents/pointerevent_pointerrawupdate.html?label=master&product=firefox%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D)

- [ ] Firefox: [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1550462)
- [ ] Safari: [Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=210454)

## [`ResizeObserverEntry.devicePixelContentBoxSize`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/devicePixelContentBoxSize)

Relevant PR: #2859.
[MDN Compatibility Table](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/devicePixelContentBoxSize#browser_compatibility)
[Caniuse](https://caniuse.com/mdn-api_resizeobserverentry_devicepixelcontentboxsize)
[WPT](https://wpt.fyi/results/resize-observer/devicepixel.html?label=master&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D)

- [ ] Safari: [Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=219005)

## [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) initial size

Relevant PR: #2859.
[WPT (test 16)](https://wpt.fyi/results/resize-observer/observe.html?label=master&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D)

- [ ] Safari: [Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=251015)
  - [x] Fixed in Safari 17 beta!

**Comment by daxpedda** [comment]
`Window.requestIdleCallback()` is now enabled by default on Safari TP: https://github.com/WebKit/WebKit/pull/16538.
